database:
  host: 0.0.0.0
  port: 3307
  username: root
  password: password
  database: shoe

api:
  host: 0.0.0.0
  port: 9003

otp:
  sender: shoestoresevice111@gmail.com
  password: lvlc hnck fpxl ibwi
